### PR TITLE
Put PSF into en and zh-tw.

### PR DESCRIPTION
**Pull request by drakeguan**

### CODE REVIEW

**Comment by ccwang002** [comment]
thanks!

**Comment by drakeguan** [comment]
How to upload psf.png?

On Fri, Apr 4, 2014 at 5:18 PM, Liang Bo Wang notifications@github.comwrote:

> thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pycontw/PyconAPACDraft/pull/40#issuecomment-39545878
> .

## 

Shuen-Huei (Drake) Guan
R&D Manager, Digimax, Inc. / Sponsorship Chair, PyConAPAC/TW 2014
http://about.me/drakeguan

**Comment by ccwang002** [comment]
Either send to me or give a pull request to the [web backend](https://bitbucket.org/pycontw/pycon-apac-2014)

**Comment by drakeguan** [comment]
Quick question:

Why are there two separated repo, one for draft and the other for web
backend?

On Fri, Apr 4, 2014 at 5:55 PM, Liang Bo Wang notifications@github.comwrote:

> Either send to me or give a pull request to the web backendhttps://bitbucket.org/pycontw/pycon-apac-2014
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pycontw/PyconAPACDraft/pull/40#issuecomment-39548673
> .

## 

Shuen-Huei (Drake) Guan
R&D Manager, Digimax, Inc. / Sponsorship Chair, PyConAPAC/TW 2014
http://about.me/drakeguan

**Comment by ccwang002** [comment]
Frontend used to edit like wordpress, no repo needed.
But I found that during collaboration, it may lost some history and the editor makes html code in a mess, so I put all web pages here as a version control

**Pull request merged**
